# Configuración básica de Jekyll
title: k8spulse Documentation
description: Documentation for k8spulse - A Critical Kubernetes Cluster Health Dashboard
baseurl: "" # Para GitHub Pages, si tu sitio está en la raíz del repositorio
url: "https://raestrada.github.io/k8sPulse/" # Tu dominio
remote_theme: just-the-docs/just-the-docs # Tema remoto Just the Docs

# Configuración de Markdown y conversión
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Archivos y carpetas a excluir
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Configuración del layout por defecto
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
